name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Create a JS file with your API key from the secret
      - name: Inject Google Maps API key
        run: |
          echo "const API_KEY = '${{ secrets.GOOGLE_MAPS_API_KEY }}';" > ./config.js

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        # Assuming you have a GitHub Pages deployment action or script here
