# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Inject the Google Maps API key into config.js
      - name: Inject Google Maps API key
        run: |
          echo "const API_KEY = '${{ secrets.GOOGLE_MAPS_API_KEY }}';" > ./config.js

      # Continue with your deployment steps here (e.g., deploy to GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Adjust the directory based on your build output
